### ISSUE TITLE
Error on reference when we use ghr38 version 90

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [pachterlab/sleuth#138]
I try to use kallisto and then  sleuth. When I use sleuth_prep I have this error:

[Warning message:
In check_target_mapping(tmp_names, target_mapping) :
  intersection between target_id from kallisto runs and the target_mapping is empty. attempted to fix problem by removing .N from target_id, then merging back into target_mapping. please check obj$target_mapping to ensure this new mapping is correct.
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=it_IT.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2
> 

](url)

**Comment by lynnyi** [comment]
Hi,

It means the transcript names between your index and your transcript to gene mapping are not matching.  This often times occur because one of the two has a trailing .N where N is a number in the transcript name modifier. Check that the transcript names match between your transcript to gene map and your original transcriptome, or that your transcript to gene map is set up correctly.


Best,
Lynn

**Comment by warrenmcg** [comment]
Hi @bioinfo-dirty-jobs,

Are you using biomaRt or something else to get your annotations? I usually have to get both the `ensembl_transcript_id` and `transcript_version` when using biomaRt's `getBM`. Then, if my annotations table is called `annos`, I have to concatenate them using
```
annos$target_id <- paste(annos$ensembl_transcript_id, annos$transcript_version, sep = ".")
```
This avoids the warning you're getting.

If you're not bothered by the warning, you should otherwise not have an issue.
