### ISSUE TITLE
transformation_function not working

### ISSUE THREAD

**Issue by dominik-handler** [pachterlab/sleuth#200]
Hi,

I tried to change the transformation function, but no matter what function I supply the results stay the same. This is the code I use:
  ```
 so <- sleuth_prep(s2c, ~condition, target_mapping = t2g, aggregation_column = 'ens_gene',
                    extra_bootstrap_summary = TRUE,
                    transformation_function = function(x) log2(x + 0.5),
                    read_bootstrap_tpm = TRUE,  ## required if sleuth_fit uses which_var = "obs_tpm"
                    gene_mode = TRUE) ##use old method and not p-value aggregation
  
```
Thank you,
Dominik

**Comment by dominik-handler** [comment]
Yes, it was the latest release version.
Is there another version in ehich the TPMs would get transformed?

Thank you.

Am 21.09.2018 12:26 Vorm. schrieb Warren McGee <notifications@github.com>:

What version are using (stable, devel, or a specific patch (commit would be helpful))? In the stable version, the TPMs were not transformed, so changing the transformation_function argument only changes how the counts are transformed.

**Comment by warrenmcg** [comment]
The latest commit on the master branch has the expected functionality, so you can just re-run `devtools::install_github('pachterlab/sleuth', ref = 'master')` to get the latest version. Or if you are comfortable running a patched devel version, you could install the latest devel `devtools::install_github('warrenmcg/sleuth', ref = 'd73306').

In both, the `transformation_function` has now become two separate options: `transform_fun_counts` and `transform_fun_tpm`. The new documentation for sleuth_prep (accessed by `?sleuth_prep`) is hopefully clear on this and on other new options.

Since I think we've answered your problem, I'm going to close this issue. If you have a new error that comes up as a result of using either the latest master or the devel, feel free to reopen this issue or open a new one.

**Comment by dominik-handler** [comment]
Hi,

I tried your suggestsions, but it did not work out. I installed the version from the master branch and ran the analysis using this command:

  ```
  so <- sleuth_prep(s2c, ~condition, target_mapping = t2g, aggregation_column = 'ens_gene',
                    extra_bootstrap_summary = TRUE,
                    transformation_function_reads=function(x) log2(x + 0.5),
                    transformation_function_tpm=function(x) log2(x + 0.5),
                    read_bootstrap_tpm = TRUE,  ## required if sleuth_fit uses which_var = "obs_tpm"
                    gene_mode = TRUE) ##use old method and not p-value aggregation
```
Still I got back b-values in natural log. I also tried it using only the function for reads or tpm. I then tested something and forked sleuth and changed the function manually to log2 and the tpm-function from identity to the function. Then it works. Does sleuth still not use my supplied function, or do I supply it in a wrong format. 

Thank you,
Dominik

**Comment by warrenmcg** [comment]
Hi @dominik-handler, 

You used `transformation_function_reads` and `transformation_function_tpm`. These are not the correct arguments; please use `transform_fun_counts` and `transform_fun_tpm`. Let me know if you continue to have problems after that.

Also, I should note that if you simply care about getting log2 fold changes for `b`, as an alternative, you can simply do what DESeq2 does and do a post-hoc conversion: `log2(e) * b` (see [this line of code in DESeq2's internal methods](https://github.com/mikelove/DESeq2/blob/600c6c20fca6c2d54148bea17ac31c424ac69336/R/fitNbinomGLMs.R#L177)).

**Comment by dominik-handler** [comment]
A, damn. Missed that completely. Did not pay attention to the exact wording. Copied it from somewhere.

Thank you,
Now it works perfectly fine.

Dominik
