### ISSUE TITLE
subsetting kallisto object using subset_kallisto()

### ISSUE THREAD

**Issue by PocketChangeJ** [pachterlab/sleuth#201]
Hi,
I'm struggling with subset_kallisto(), which I'm trying to use to subset a list of transcripts from the sleuth object.. It seems i'm not providing the list to subset correctly. Would it be possible for you to provide an example of how to do that correctly, or help me figure out what I'm doing incorrectly?
Thank you so much!
I'm trying:
`target_id <- c("ENSMUST00000000001", "ENSMUST00000000003", "ENSMUST00000000129")
so_subset <- subset_kallisto(so, target_ids = target_id)`

**Comment by warrenmcg** [comment]
Hi @PocketChangeJ,

What are you expecting to do with the subset versus the full sleuth object? The `subset_kallisto` function is not intended to subset the full sleuth object. Instead, it only modifies the `so$kal` item in the sleuth object. The returned object is a subset of the kallisto object (or list of kallisto objects in the case of `so$kal`).

The typical pipeline for this to work well is to do the following. If you have the path to the kallisto HDF5 file you want to subset stored in `kal_path`, then you can do the following code:
```
kal <- sleuth::read_bootstrap(kal_path, read_bootstrap = TRUE)
ids <- c("ENSMUST00000000001", "ENSMUST00000000003", "ENSMUST00000000129")
subset_kal <- sleuth::subset_kallisto(kal, target_ids = ids)
## now you have a subsetted object which you can write to a new file
write_kallisto_hdf5(subset_kal, fname = "subset_kal.h5")
```

I would guess that this won't work well from the `so$kal` list because in the current implementation, the `so$kal` list of kallisto objects does not have bootstraps stored, so those will be missing when you do the subsetting.

Let me know if this helps!

**Comment by PocketChangeJ** [comment]
Hi @warrenmcg, thank you. We are trying to quantify xenografts, so looking to split hdf5 file based on the species.

**Comment by warrenmcg** [comment]
Hi @PocketChangeJ,

Thank you for giving your use case! It is an important one and probably frequent one indeed! One could also think about microbiome experiments or other experiments where cross-species contamination is to be expected.

If the intended pipeline doesn't work for you, or if you want to request a feature related to this, feel free to re-open this issue or open another one.
