### ISSUE TITLE
Distribute `sleuth_live(so)` onto a Shiny Server

### ISSUE THREAD

**Issue by tinyheero** [pachterlab/sleuth#22]
The `sleuth_live(so)` is fantastic. 

I place my shiny apps into /srv/shiny-server. What is the correct/best way to distribute the `sleuth_live(so)` onto a shiny server?

Thanks

**Comment by pimentel** [comment]
hi @tinyheero really glad you like it. thanks for the kind words!

i've been meaning to try it for some time but haven't had time to setup a server. I believe the way to do it is as follows:

- prepare your `so` up to the point where you can run `sleuth_live` on it
- save the object to some directory. we'll call it `shiny/sleuth` where your other shiny apps live at shiny
   - `saveRDS(so, file = 'shiny/sleuth/so.rds')`
- place the following code in `shiny/sleuth/app.R`:

```{r}
so <- readRDS('shiny/sleuth/so.rds')
sleuth::sleuth_live(so)
```

This should work since `sleuth_live` returns a proper `shinyApp` object

That should do it. if you have some time/curiosity, i'd be really happy to hear your experience. if this doesn't work, i'll give it a shot later this week.

Note that everytime the shiny app is started it has to read in the sleuth object, so it will definitely not start up as fast as it does on your local machine.

**Comment by tinyheero** [comment]
Got it working. Thanks! A small amendment to that code:

```
library("sleuth")
so <- readRDS('shiny/sleuth/so.rds')
sleuth_live(so)
```

So that ggplot2 will get loaded (as sleuth depends on it) so that plotting works. 

Great work again on the Shiny App. This should be the gold standard on how bioinformatic results get distributed.

**Comment by pimentel** [comment]
Thanks a bunch for trying this -- I'm happy to hear it worked!

So I can get a feel for runtime, how long does it take for the shiny app to launch once you hit the website? Also, how big is your dataset (how many transcripts, what org, how many bootstraps)?

I think we might end up making a special serialization of the sleuth object for distributing shiny apps, because I fear that large datasets seem to load up slow using the standard R serialization.

**Comment by tinyheero** [comment]
It's not too bad. Loading time was ~2 mins for an .rds file ~ 1.3G. 

My sample set is consists of 6 samples and uses `Homo_sapiens.GRCh38.rel79.cdna.all.fa.gz` file (used the link from kallisto website). I used `-b 100` in kallisto.

As it should be a one-time loading, what might help is some kind of "loading bar". So that users would be informed on how what is happening. Also, is it easy to "extend" this shiny application? I am interested in placing more information into the shiny app for collaborators to look at.

**Comment by jianwang2014** [comment]
Hi Tinyheero:  I am glad you got it working.  Unfortunately, I have a few dozen samples and the app won't start up before I am timed out. -JW

**Comment by pimentel** [comment]
@jianwang2014, as noted on the google group, we are actively working to reduce the memory for large samples. we should have a prototype in the coming weeks.

**Comment by pimentel** [comment]
@jianwang2014 we have now made this a formal issue and have 1 person working on it full-time. we hope to have it coming within relatively soon.

https://github.com/pachterlab/sleuth/issues/40

**Comment by FloWuenne** [comment]
Hi everybody,
first of all, thanks so much for kallisto and sleuth, I really love working with both of those tools! 
This thread helped me a lot initially to realize how to host the sleuth objects on a shiny server. While trying to deploy my sleuth servers to shinyapps.io however, I ran into an issue that I was not able to fix so far. 

When deploying a sleuth app to shinyapps.io, it tries to build the rhdf5 package:
    building: Building package: rhdf5
    Building R package: rhdf5 (2.18.0)
    installing *source* package ‘rhdf5’ ...
However this does not seem to be possible on the shinyapps.io server. 
    myhdf5.h:7:27: fatal error: hdf5/src/hdf5.h: No such file or directory
    #include "hdf5/src/hdf5.h"
                           ^
    compilation terminated.
    make: *** [HandleListWrap.o] Error 1
    make: *** Waiting for unfinished jobs....
    In file included from H5E.h:8:0,

Could this issue be solved by creating an issue on [shinyapps-package-dependencies
](https://github.com/rstudio/shinyapps-package-dependencies) to include hfd5source in their packages?

Thanks!

**Comment by pimentel** [comment]
@FloWuenne 

I'm sorry missed this when it happened...

Anyway, are you still having these issues? I've been wanting to deploy on shinyapps.io myself so I will probably give it a try soon.

I'd like to follow through with this because I think it would be pretty cool to get stuff hosted there.



Thanks,

Harold

**Comment by FloWuenne** [comment]
@pimentel 

No problem! We tried this hosting on shinyapps.io as part of a teaching course. It was actually an issue on the side of shinyapps.io as rhdf5 could not be build on their servers. I contacted the shinyapps.io team and thanks to @jspiewak this issue is now resolved and deploying sleuth shiny apps to shinyapps.io works without problems!!!

So I guess we can close this issue as resolved! :)

**Comment by pimentel** [comment]
hey that's great news!

thanks to everyone involved!

**Comment by umasstr** [comment]
Has anyone hosted a sleuth object recently? 

Error fetching Rhdf5lib (1.4.3) source. Error downloading package source.
