### ISSUE TITLE
problem installing sleuth

### ISSUE THREAD

**Issue by Kappy2** [pachterlab/sleuth#241]
I finally got bioconductor to install. Now I have this error message when trying to install sleuth.
> BiocManager::install("pachterlab/sleuth")

Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.2 (2019-12-12)
Installing github package(s) 'pachterlab/sleuth'
Error: Failed to install 'unknown package' from GitHub:
  Problem with the SSL CA cert (path? access rights?)

Someone please help me, I have been at this for the past week, first installing newest R, then trying to get bioconductor to work. I am so close... (Had to start everything from scratch because previous version of R was not up to date...can you sense the despair?) THANK YOU

**Comment by clydeandforth** [comment]
Hi Kappy2,

I think you have to install devtools and rhdf5 first then install Sleuth via devtools as described here:

https://pachterlab.github.io/sleuth/download

**Comment by racng** [comment]
The line `source("http://bioconductor.org/biocLite.R")` from the sleuth manual is not working for R version >3.5 because it now requires BiocManager to install Bioconductor packages. 
Here are updated instructions for installing sleuth (only changing the first step):
1) Install rhdf5:
```
BiocManager::install("rhdf5")
```
2) Install devtools:
```
install.packages("devtools")
```
3) Install sleuth:
```
devtools::install_github("pachterlab/sleuth")
```
