### ISSUE TITLE
fold-change value in sleuth_result.txt

### ISSUE THREAD

**Issue by shrukane** [pachterlab/sleuth#59]
Hi,
I have a question about the sleuth_result.txt file generated from the tool. Is there a column that tells us the fold change or log2 in the file ? If not is there a workaround this ?
Regards
Shruti

**Comment by pimentel** [comment]
@shrukane sorry for the delayed response. there is not, and part of the reason is because the `beta` value is the effect size on the log transformed data. Because of this, you can't really get back the log2 (E[log(X)] != log(E[X]) in general).

Some people have done the following: `log2(exp(beta))` but I strongly suggest against this as it will give you a biased estimate.

I believe in the next version we will probably change from natural log to log base 2

**Comment by shrukane** [comment]
I see. Thank you for your help @pimentel

**Comment by leiendeckerlu** [comment]
Anything new on this? Still intending to switching to log base 2 ?

**Comment by pimentel** [comment]
in the latest version you can do the following:

```
sleuth_prep(........, transformation_function = function(x) log2(x + 0.5))
```

**Comment by roryk** [comment]
Awesome, thanks Harold!

**Comment by CristinaOsu** [comment]
Hi,

Is there any update on this issue? I am trying to do a fair comparison of the Differential expression results that I have obtained using both Sleuth and EgdeR, but I cannot compare directly e.g. beta values vs. log fold changes, right? I was wondering if there is an easy way to do the conversion, or if there is an update in this issue in the last version of Sleuth to retrieve the log fold changes. Would you mind to better explain your previous answer with a practical example (sleuth_prep(........, transformation_function = function(x) log2(x + 0.5))) @pimentel?

Thank you so much in advance,

Cristina

**Comment by YichaoOU** [comment]
@CristinaOsu Did you get an answer to this logFC problem? 

Thanks!
