### ISSUE TITLE
Error connecting to ensembl

### ISSUE THREAD

**Issue by Lila14** [pachterlab/sleuth#83]
I ran

```
> mart <- biomaRt::useMart(biomart = "ENSEMBL_MART_ENSEMBL",
+   dataset = "hsapiens_gene_ensembl",
+   host = 'ensembl.org')
> t2g <- biomaRt::getBM(attributes = c("ensembl_transcript_id", "ensembl_gene_id",
+     "external_gene_name"), mart = mart)
```

and received the following error:

> Error in biomaRt::getBM(attributes = c("ensembl_transcript_id", "ensembl_gene_id",  : 
>   Query ERROR: caught BioMart::Exception::Database: Could not connect to mysql database ensembl_mart_85: DBI connect('database=ensembl_mart_85;host=martdb.local.cloud.local;port=3306','ensro',...) failed: Can't connect to MySQL server on 'martdb.local.cloud.local' (111) at /ensemblweb/www/www_85/biomart-perl/lib/BioMart/Configuration/DBLocation.pm line 98.

However, ensembl seems to work when I run the following (as described [here](http://useast.ensembl.org/info/docs/api/debug_installation_guide.html)):

`$ perl ensembl/misc-scripts/ping_ensembl.pl`

I get the following output:

>  Installation is good. Connection to Ensembl works and you can query the human core database
> ERROR: Error detected when connecting to Ensembl!
>   Your core installation was good but supplementary modules cannot be found. If you wish to access these other Ensembl resources add the libraries to your PERL5LIB:
>   Missing the checkout Compara
>   Missing the checkout Variation
>   Missing the checkout Funcgen

**Comment by nicolasbray** [comment]
Hi there,

It looks like there's been an update somewhere that's causing biomaRt to
fail. Updating the biomaRt package seems to have fixed the problem on my
end.

Best,
Nick

**Comment by Lila14** [comment]
Thanks, this worked.

**Comment by warrenmcg** [comment]
biomaRt may have been outdated, or the Ensembl server may have been down for periodic maintenance. I received this exact error yesterday, and the latter turned out to be the issue.

For future reference, you can always go to the Ensembl's blog to find out if they are doing server maintenance. If they are, then the servers will be down and biomaRt will not be able to retrieve the information it needs until they finish maintenance.

The blog is here: http://www.ensembl.info
