### ISSUE TITLE
sleuth_to_matrix reports transcripts even when an aggregation_column was provided to sleuth_prep

### ISSUE THREAD

**Issue by rspreafico** [pachterlab/sleuth#84]
sleuth_prep accepts an aggregation_column parameter which is used for differential testing, however the function sleuth_to_matrix does not honor that parameter and always returns transcripts. sleuth v0.28.1

**Comment by warrenmcg** [comment]
I've submitted a pull request (#99) that changes the behavior of sleuth to report gene level estimates for the `obs_norm` parameter of the `sleuth` object, which is what is converted to a matrix using `sleuth_to_matrix`. I did not touch the `obs_raw` object, but maybe it can be updated to report gene-level raw scaled estimates? I have not done that yet.

I have not incremented the version number on my forked repository, but you can try using my updated sleuth package there if you still need to perform this task with the expected behavior of having gene-level results.

Can't provide guarantees, but hopefully worth checking out.

if you need help with how to do the installation:
```
devtools::install_github("warrenmcg/sleuth", with_libpaths="nondefault/library/location")
```

**Comment by pimentel** [comment]
fixed a while ago by @warrenmcg
