### ISSUE TITLE
Scatter plot hyphen bug

### ISSUE THREAD

**Issue by PeterVenhuizen** [pachterlab/sleuth#89]
Some of my samples have hyphens in their names, which works fine, except for generating the scatter plots, see the attached image. The easy solution would of course be to change my sample names, but it would be nice if it would work! 

![sleuth_hyphen_bug](https://cloud.githubusercontent.com/assets/11519125/21105504/c17cc1e0-c08a-11e6-928d-077b418d8b28.png)

**Comment by warrenmcg** [comment]
Hi @PeterVenhuizen,

Hyphens are a tricky thing in R because they're interpreted as minus signs. So, your combination of hyphens and underscores leads to a syntax error (you can see the exact same error if you try typing in `7-1-1_A` at the R interactive prompt without quotes). I made a proposed change to `plot_scatter` that should alleviate this problem. For the time being, you can either (A) wait for the change to be incorporated into the next release, (B) incorporate the change into your own code, or (C) change your names to not have hyphens.

Hope this helps!
Warren

**Comment by pimentel** [comment]
Fixed in the latest version by @warrenmcg!

Thanks again!
