### ISSUE TITLE
dim(X) must have a positive length

### ISSUE THREAD

**Issue by ro6ert** [pachterlab/sleuth#90]
Hello,

I am running sleuth on some data created from Wasabi and Salmon run with 100 bootstraps. I tried to google the error message, but the issue I found had only 1 contig rather than 65k so I don't think it applies.

Thankyou,
-Rob

`> s2c <- data.frame(pathsamplecondition,stringsAsFactors=FALSE)
> so <- sleuth_prep(s2c, ~Lc.Batch+Age_Enroll+race+gender+ATS_PackYears+neutrophl_pct+eosinphl_pct+lymphcyt_pct+monocyt_pct+SmokCigNow, max_bootstrap = 5)
reading in kallisto results
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
normalizing est_counts
67478 targets passed the filter
Error in apply(mat_nz, 1, function(row) mean(log(row))) : 
  dim(X) must have a positive length
Calls: sleuth_prep -> norm_fun_counts -> apply
Execution halted`

**Comment by warrenmcg** [comment]
Hi @ro6ert,

There is some need for more information before we can solve your problem. The `norm_fun_counts` method (actually, `norm_factors`) does a filtering step that removes all rows that have all zero counts. It appears the error here is implying that all of your rows have zero counts. This is indeed an odd result, since you had 67K transcripts pass the filter.

If you have Rstudio, you can use the `debugonce` function to dive into the `sleuth_prep` method like this:
```
debugonce(sleuth_prep(s2c, ~Lc.Batch + Age_Enroll + race + gender + 
                            ATS_PackYears + neutrophl_pct + eosinphl_pct + 
                            lymphcyt_pct + monocyt_pct + SmokCigNow, 
          max_bootstrap = 5))
```
Once you have the debugger launched, use this tutorial to debug the code and figure out what the problem may be: [Debugging with Rstudio](https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio#stopping-when-a-function-executes)

If you don't have Rstudio or another IDE, I recommend you get one, as it makes your life working with R much easier.
